### ISSUE TITLE
Problemas en la rama Modulo1Tania

### ISSUE THREAD

**Issue by TaniaAlvarezDiaz** [Arquisoft/Loader_e5a#1]
En la rama Modulo1Tania están implementadas todas las modificaciones, así como las pruebas que se piden para esta primera parte del proyecto.
Hay pruebas que no pasan los test, debido a lo que he podido observar, a problemas con la base de datos, en concreto, con clases que no encuentra o problemas con atributos de alguna clase, como es el caso del atributo "location" en la clase "User".
Me gustaría que alguien mirara el código y diera su opinión, ya que no se si está bien o falta funcionalidad.
Por otra parte también me gustaría que si alguien sabe como solucionar los problemas de los test me lo dijera, para así poder corregirlos.

**Comment by UO204115** [comment]
Llevo 1 hora intentándolo pero no he conseguido clonar tu rama para poder hacer pruebas con ella, de hecho estuve haciendo pruebas con lo que creía que era tu rama hasta que me di cuenta que me había bajado la master por error así que ignora ese commit. ¿Cómo sería la instrucción para poder bajarme esta rama? Porque he probado de todo y no lo he conseguido. A una mala mañana copio clase por clase el código y lo reviso

**Comment by UO204115** [comment]
Tania ya he localizado el error, pero desde este PC de la universidad es una tortura hacer cambios, se cuelga cada poco. El fallo está en que el mapeador de Users es incapaz de encontrar la clase Location porque no está mapeada. En principio si la incluímos en la BD y la mapea ya no tendríamos el fallo y el código debería funcionar porque no le vi más errores salvo algún warning que eliminé

**Comment by AlexBarreraSanchez** [comment]
Vale, rama Modulo1Tania todos los tests pasando.
He añadido las anotaciones al modelo, corregido en RList el load para que acepte celdas en blanco. También he corregido algun error de formato y he formateado algunas clases. Puedes cerrar el issue.
