### ISSUE TITLE
Modificaciones Tania en la documentacion entrega 2

### ISSUE THREAD

**Issue by TaniaAlvarezDiaz** [Arquisoft/Loader_e5a#8]
He modificado las siguientes secciones en la documentación:

- Apartado 2 Requisitos
   - Modifique que el sistema esta formado por 3 partes en vez de 2, y añadi la explicacion de las partes que faltaban que nos corresponde a nuestro grupo.

- Apartado 9 Vistas
  - Actualice la tabla con los dos nuevos sistemas, he puesto los stakeholders y algun atributo de calidad.
  - Me gustaria que revisarais estos datos, si estan bien hay que modificar el apartado 5.1 entre otros.

- Apartado 9.1.2.1 Elementos
  - Añadi los nuevos elementos con la correspondiente informacion.

- Actualize el indice para que se correspondiera con los cambios introducidos

También quería comentaros que creo que en el apartado 9.1.1; 9.2.2.3 y 9.3 habria que quitar los opcionales.

**Comment by TaniaAlvarezDiaz** [comment]
He añadido dos atributos de calidad, el AT017 y el AT018, ambos relacionados con la seguridad. Tras añadirlos he modificado las secciones correspondientes:

- La tabla del apartado 5.2

- 8.Escenarios de calidad, añadiendo los escenarios 17 y 18 respectivamente.

- El apartado 9, añadiendo dichos atributos y escenarios en la fila de la tabla que se corresponde con InciManagement.

**Comment by TaniaAlvarezDiaz** [comment]
- He modificado la figura 3 del punto 9.1.1. He añadido los subsistemas. Falta por completar las interfaces que los unen asi como ponerles los correspondientes nombre, de momento, lo he dejado con Nombre1, Nombre2, etc.

- En el apartado 9.1.2.1 he añadido como elemento Apache Kafka con sus propiedades.

- En el apartado 9.1.2.4.4 he añadido la descripción de InciManager.

- He añadido el apartado 9.1.2.4.5 sobre Apache Kafka.

- En el apartado 9. Vistas he puesto el 9.2 como Sistema de gestión de usuarios, y en él he metido el Loader y Agents, ya que estos forman un módulo en conjunto.

- He añadido el apartado 9.3.2.1.Elementos de InciManager.

**Comment by IsmaCadenas** [comment]
- He añadido el apartado 2.2 
- He añadido el diagrama de componentes al apartado 9.3.1, falta completar nombres.
- He añadido el comportamiento de los elementos al apartado 9.3.2.4
